# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-27 13:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=20, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=190, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]+$', '숫자만 입력 가능합니다.', 'invalid')], verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='필수입니다. 영문소문자, 숫자와 밑줄(_)만 입력가능합니다.', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(32), django.core.validators.RegexValidator('^(?!_)[a-zA-Z0-9_]+$', '영문소문자, 숫자와 밑줄(_)만 입력가능합니다.', 'invalid')], verbose_name='username'),
        ),
    ]
